### ISSUE TITLE
Do we have a en-us version of "building-secure-scalable-and-highly-available-magento-stores..."?

### ISSUE THREAD

**Issue by joeashcraft** [rackerlabs/rackspace-white-paper#18]
Was there, by chance, an English version of [this page](https://github.com/rackerlabs/rackspace-white-paper/blob/master/content/white-paper/building-secure-scalable-and-highly-available-magento-stores-powered-by-rackspace.html)?

**Comment by stephamon** [comment]
@joeashcraft I'm sure there was! I've stumbled across a few of these before, and felt sure that there were more out there. I'll add the English version back to the site. Thanks for catching it!

**Comment by stephamon** [comment]
@joeashcraft I've published the English version, which you can see here: https://support.rackspace.com/white-paper/building-secure-scalable-and-highly-available-magento-stores-powered-by-rackspace/
