### ISSUE TITLE
Some white papers redirect to /how-to/ instead of staying in /white-paper/

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/rackspace-white-paper#8]
Quite by accident, I discovered that if you go to support.rackspace.com/white-paper/ and start clicking around on the white paper links, some of them are trying to go back to /how-to/ instead of /white-paper/.

For example, if you click on the "The Ecommerce Customer Experience Guide" white paper, it tries to go to: https://support.rackspace.com/how-to/the-ecommerce-customer-experience.

If you try changing `/how-to/` to `/white-paper/` (as is the format for white papers), it goes to a 404. The white paper does live in this repo (I checked), so I'm not sure why some of them are trying to go to the How-To site instead of staying in the white papers section.

**Comment by ktbartholomew** [comment]
Fixed w/ https://github.com/rackerlabs/rackspace-white-paper/pull/10
